product-service:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
    OkToRetryOnAllOperations: true # 是否对所有操作都进行重试
    MaxAutoRetriesNextServer: 2 # 切换实例的重试次数
feign:
  hystrix:
    enabled: true
management:
  endpoints:
    web:
      exposure:
        include: '*'
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000 #默认的连接超时时间1秒,若1秒没有返回数据,自动的触发降级逻辑
      circuitBreaker:
        enabled: true
        requestVolumeThreshold: 5 #触发熔断的最小请求次数，默认20
        errorThresholdPercentage: 10 #触发熔断的失败请求最小占比，默认50%
        sleepWindowInMilliseconds: 10000 #熔断多少秒后去尝试请求，默认是5S
spring:
  rabbitmq:
    host: 106.13.208.154
    virtual-host: java1907
    username: yu
    password: 123
